name: Scheduled Form-Submit
permissions: 
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  submit:
    runs-on: ubuntu-latest
    env:
      HEADLESS: "true"
      GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
      
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        persist-credentials: true
  
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
  
    - name: Install dependencies
      run: npm ci
  
    - name: Install Playwright browsers
      run: npx playwright install
  
    - name: Run form-fill
      run: npm run testRun

    - name: Commit serviceRequest.log
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add serviceRequest.log
        git commit -m "chore: append new serviceRequest log entry" || echo "No changes to commit"
        git push 